Repository moonnnnnnn2541354/trello, pull requests merged in 2024-01, with the labels that each got.

#14 Card
  src/main/java/com/sparta/trellor/domain/card/controller/CardController.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/entity/Card.java
  src/main/java/com/sparta/trellor/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/trellor/domain/card/service/CardService.java
  src/main/java/com/sparta/trellor/domain/column/entity/BoardColumn.java
Labels: feat

#15 refactor: Column_ column_no 생성 기능 수정
  src/main/java/com/sparta/trellor/domain/board/entity/Board.java
  src/main/java/com/sparta/trellor/domain/column/entity/BoardColumn.java
  src/main/java/com/sparta/trellor/domain/column/service/BoardColumnService.java
Labels: refactor

#16 refactor: Exception 기능 구현 / feat: Comment 부분 Exception 구현
  src/main/java/com/sparta/trellor/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/trellor/domain/comment/dto/msg/MessageDeleteDto.java
  src/main/java/com/sparta/trellor/domain/comment/dto/msg/MessageResponseDto.java
  src/main/java/com/sparta/trellor/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/com/sparta/trellor/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/sparta/trellor/domain/comment/exception/CommentExistsException.java
  src/main/java/com/sparta/trellor/domain/comment/service/CommentService.java
  src/main/java/com/sparta/trellor/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/trellor/global/exception/error/CommonErrorCode.java
  src/main/java/com/sparta/trellor/global/exception/error/ErrorCode.java
  src/main/java/com/sparta/trellor/global/exception/error/ErrorResponse.java
  src/main/java/com/sparta/trellor/global/exception/error/RestApiException.java
Labels: feat, refactor

#17 feat: 카드 조회 기능 추가
  src/main/java/com/sparta/trellor/domain/card/controller/CardController.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/trellor/domain/card/service/CardService.java
  src/main/java/com/sparta/trellor/domain/comment/repository/CommentRepository.java
Labels: feat

#19 Feat/add user exception
  src/main/java/com/sparta/trellor/domain/user/controller/UserController.java
  src/main/java/com/sparta/trellor/domain/user/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/response/UserMessageResponseDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sparta/trellor/domain/user/entity/User.java
  src/main/java/com/sparta/trellor/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/trellor/domain/user/exception/UserExistsException.java
  src/main/java/com/sparta/trellor/domain/user/service/UserService.java
  src/main/java/com/sparta/trellor/global/security/JwtAuthenticationFilter.java
  src/test/java/com/sparta/trellor/domain/user/dto/request/SignupRequestDtoTest.java
  src/test/java/com/sparta/trellor/global/jwt/JwtUtilTest.java
  src/test/java/com/sparta/trellor/test/CommonTest.java
  src/test/resources/application-test.properties
Labels: feat

#20 style: BoardFindColumnResponseDto 클래스명 수정
  src/main/java/com/sparta/trellor/domain/board/dto/BoardFindColumnResponseDto.java
Labels: style

#21 Card
  src/main/java/com/sparta/trellor/domain/card/controller/CardController.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/trellor/domain/card/dto/msg/CardMessageDeleteDto.java
  src/main/java/com/sparta/trellor/domain/card/dto/msg/CardMessageResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/entity/Card.java
  src/main/java/com/sparta/trellor/domain/card/exception/CardErrorCode.java
  src/main/java/com/sparta/trellor/domain/card/exception/CardExistsException.java
  src/main/java/com/sparta/trellor/domain/card/service/CardService.java
  src/main/java/com/sparta/trellor/domain/column/controller/BoardColumnController.java
  src/main/java/com/sparta/trellor/domain/column/entity/BoardColumn.java
  src/main/java/com/sparta/trellor/domain/column/service/BoardColumnService.java
Labels: feat

#22 fest: Test 구현 / refactor: BoardFindColumnResponseDto @Builder 어노테이션 삭제
  src/main/java/com/sparta/trellor/domain/board/dto/BoardFindColumnResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/trellor/domain/card/entity/Card.java
  src/test/java/com/sparta/trellor/util/BoardColumnTest.java
  src/test/java/com/sparta/trellor/util/BoardTest.java
  src/test/java/com/sparta/trellor/util/CardTest.java
  src/test/java/com/sparta/trellor/util/CommonTest.java
  src/test/java/com/sparta/trellor/util/ControllerTest.java
Labels: feat, refactor

#23 Style: 파일 전체 주석문 제거 및 정렬
  src/main/java/com/sparta/trellor/domain/board/controller/BoardController.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardCreateRequestDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardCreateResponseDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardFindColumnResponseDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardInviteRequestDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardInviteResponseDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardReadAllResponseDto.java
  src/main/java/com/sparta/trellor/domain/board/dto/BoardReadResponseDto.java
  src/main/java/com/sparta/trellor/domain/board/entity/Board.java
  src/main/java/com/sparta/trellor/domain/board/entity/UserBoard.java
  src/main/java/com/sparta/trellor/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/trellor/domain/board/repository/UserBoardRepository.java
  src/main/java/com/sparta/trellor/domain/board/service/BoardService.java
  src/main/java/com/sparta/trellor/domain/card/Test.java
  src/main/java/com/sparta/trellor/domain/card/controller/CardController.java
  src/main/java/com/sparta/trellor/domain/card/dto/CardResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/dto/CommonResponseDto.java
  src/main/java/com/sparta/trellor/domain/card/exception/CardExistsException.java
  src/main/java/com/sparta/trellor/domain/card/service/CardService.java
  src/main/java/com/sparta/trellor/domain/column/controller/BoardColumnController.java
  src/main/java/com/sparta/trellor/domain/column/dto/BoardColumnMoveRequestDto.java
  src/main/java/com/sparta/trellor/domain/column/dto/BoardColumnMoveResponseDto.java
  src/main/java/com/sparta/trellor/domain/column/dto/BoardColumnRequestDto.java
  src/main/java/com/sparta/trellor/domain/column/dto/MessageDto.java
  src/main/java/com/sparta/trellor/domain/column/entity/BoardColumn.java
  src/main/java/com/sparta/trellor/domain/column/repository/BoardColumnRepository.java
  src/main/java/com/sparta/trellor/domain/comment/Test.java
  src/main/java/com/sparta/trellor/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/trellor/domain/comment/exception/CommentExistsException.java
  src/main/java/com/sparta/trellor/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/trellor/domain/comment/service/CommentService.java
  src/main/java/com/sparta/trellor/domain/dto.java
  src/main/java/com/sparta/trellor/domain/user/controller/UserController.java
  src/main/java/com/sparta/trellor/domain/user/dto/request/EmailUpdateRequestDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/request/PasswordUpdateRequestDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/response/UserMessageResponseDto.java
  src/main/java/com/sparta/trellor/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sparta/trellor/domain/user/entity/User.java
  src/main/java/com/sparta/trellor/domain/user/entity/UserRoleEnum.java
  src/main/java/com/sparta/trellor/domain/user/exception/UserExistsException.java
  src/main/java/com/sparta/trellor/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/trellor/domain/user/service/UserService.java
  src/main/java/com/sparta/trellor/domain/utils/BaseTime.java
  src/main/java/com/sparta/trellor/global/Test.java
  src/main/java/com/sparta/trellor/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/trellor/global/exception/DuplicateUsernameException.java
  src/main/java/com/sparta/trellor/global/exception/FormNotMatchException.java
  src/main/java/com/sparta/trellor/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/trellor/global/exception/TokenNotValidException.java
  src/main/java/com/sparta/trellor/global/exception/UserNotFoundException.java
  src/main/java/com/sparta/trellor/global/exception/WriterNotMatchException.java
  src/main/java/com/sparta/trellor/global/exception/error/ErrorCode.java
  src/main/java/com/sparta/trellor/global/jwt/JwtUtil.java
  src/main/java/com/sparta/trellor/global/jwt/SecurityUtil.java
  src/main/java/com/sparta/trellor/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/trellor/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/trellor/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/trellor/global/security/UserDetailsServiceImpl.java
Labels: style

#24 feat: Card-Comment @OneToMany 연관관계 맺기
  src/main/java/com/sparta/trellor/domain/card/entity/Card.java
Labels: feat

#25 style: BoardColumnService.java 주석문 제거 및 정렬
  src/main/java/com/sparta/trellor/domain/column/service/BoardColumnService.java
Labels: style
